### PR TITLE
A branch wants to merge, add date/time to order schema + CSS changes

### LINKED ISSUE #169: Post/get time attribute in every order
Include the date and time in every order in order history.

### LINKED ISSUE #179: More info on landing page about the ordering process
Give info about the whole ordering process, and info about bundle sizes

### LINKED ISSUE #182: Fix confirm email icon
No icon should be display upon start page load, only after user input will icon appear
~30 min - 1 hour

### PR DESCRIPTION
**Pull request by SpeiserK**
-Added data/time stamp to all orders, store and read from database, make it fit within liveOrder CSS and orderHist
-Update image position on some pages, add camp OAC logo and name image
-Change CSS from order page and on,,, switch from 3 div to 2
-Update about page, add more visible link, change to 2 divs
-Update navbar, add some images to fill it

close #169 
close #179 
close #182

### CODE REVIEW

**Review by camwlsn — APPROVED** [review]
Your gitstats will be ballin. Looks great

**Comment by SpeiserK** [comment]
thanks for the comment...

**Comment by camwlsn** [comment]
Using 2 divs instead of 3 looks great across pages

**Review by amurph24 — APPROVED** [review]
Looks great, 2 divs > 3 divs

**Pull request merged**
