### PR TITLE
Node mailer

### LINKED ISSUE #168: Send email to user after order is completed
Needs to be flexible, need to check square purchase validity when implemented

### PR DESCRIPTION
**Pull request by SpeiserK**
-Emails are now sent to approved orders
--Square auto "approved" orders with get an email when the order is posted (will need to change to when square API has validated the payment)
--Cash and E-Transfer orders will receive email after the order has been manually approved from employee side

I implemented the square email send function from within the order route, if anyone thinks there is a better /more efficient way to do this lemme know

Will need to install Nodemailer and update to env file

close #168

### CODE REVIEW

**Comment by SpeiserK** [comment]
Will implement denial emails on Friday, and customized email string based on location

**Review by amurph24 — APPROVED** [review]
changes look good, implementation seems to be efficient; comments are super helpful.
👍

**Review by zachpren0 — APPROVED** [review]
Excellent incorporation of nodemailer to get the emails rollin, lets send some mail!

**Comment by zachpren0** [comment]
> 
> Will need to install Nodemailer and update to env file
>

can we include this in the read me ?

**Review by camwlsn — APPROVED** [review]
Awesome work man

**Pull request merged**
