### PR TITLE
changed verbiage on banner/home/about

### PR DESCRIPTION
**Pull request by amurph24**
Verbiage changes according to Anne's email:
- Home page
- Banner
- About page

### CODE REVIEW

**Review by camwlsn — APPROVED** [review]
Nice updates. Anne will be proud

**Review by zachpren0 — APPROVED** [review]
Clients will go bananas for this 🍌

**Comment by amurph24** [comment]
> Clients will go bananas for this 🍌

🦍

**Comment by camwlsn** [comment]
🍌 🐒

**Comment by camwlsn** [comment]
> Clients will go bananas for this 🍌

🍌 🐒

**Pull request merged**
