### PR TITLE
Buggin

### PR DESCRIPTION
**Pull request by SpeiserK**
Be sure to use :  `npm uninstall nodemailer` in the backend directory to get server working again

- fix banner (kinda)
- remove nodemailer
- fix date in live orders

### CODE REVIEW

**Review by camwlsn — APPROVED** [review]
image
Great job!

**Review by zachpren0 — APPROVED** [review]
as long as the banner kinda fixed im good with it

**Comment by SpeiserK** [comment]
> as long as the banner kinda fixed im good with it

Resize a bit strange but full window looks clean

**Comment by amurph24** [comment]
Good stuff!

**Pull request merged**
