### PR TITLE
Pickup function

### LINKED ISSUE #215: Implement more order approval functionallity for employees
-Add Pickup completed button to change status of pickup on live order display and db
-Orders payed with square should immediately change Status to "Approved"

### LINKED ISSUE #216: display pickup status
display pickup status in live orders and order history

### PR DESCRIPTION
**Pull request by SpeiserK**
-add a pickup order button, which will change the status of an order in the db
-pickup status now displays on both order live and order history
-improve readability of order history
-orders done with credit/square are automatically set to "Approved"
-phone number displayed in name section

close #215 
close #216

### CODE REVIEW

**Review by camwlsn — APPROVED** [review]
This layout looks great, well done

**Review by amurph24 — APPROVED** [review]
Nice work! next we can consider having the orders move from the live orders to order history without a page refresh

**Comment by amurph24** [comment]
Will need to implement a cancel/refund order function in the future; the alternative to having the order picked up

**Comment by zachpren0** [comment]
Looks Good !

**Pull request merged**
