### PR TITLE
Delete Location.JS

### PR DESCRIPTION
**Pull request by zachpren0**
delete location page and incorporate location list into order qty.

### CODE REVIEW

**Review by SpeiserK — COMMENTED** [review]
Good idea combing the Orderqty page and Locations page. Looks great.

**Review by amurph24 — APPROVED** [review]
changes look simple, not gonna test it should be good

**Review by camwlsn — APPROVED** [review]
Nice job

**Review by SpeiserK — APPROVED** [review]
Ok, I will test

**Pull request merged**
