### PR TITLE
Tech stack init

### LINKED ISSUE #42: Create Node.js app
Start creating source files for node.js back-end application.
Install necessary libraries for a node.js server to run.
~2 hours

### LINKED ISSUE #43: Setup React js project/CRUD app
Creat React project.
-install bootstrap, react router, navbar, axioms
-create react components

### LINKED ISSUE #44: Create MongoDB account.
Need a mongoDB account to use services.
Once account has been made, can be linked to back-end node.js server.

### LINKED ISSUE #61: Installation of required software for website

### PR DESCRIPTION
**Pull request by SpeiserK**
Created Node server, linked it to MangoDB, created front end React app.

Web application is now functional and ready to start editing
close #42 
close #43 
close #44 
close #61

### CODE REVIEW

**Comment by camwlsn** [comment]
Readme had some conflicts, but they have been resolved. Good work on this

**Review by camwlsn — COMMENTED** [review]
I've reviewed the necessary files. Looks good

**Comment by amurph24** [comment]
Works for me, need to review git ignore stuff, but that can wait for another time

**Comment by zachpren0** [comment]
Looks like some good work on including all the neccesary files for running our tech stack, looks good

**Review by zachpren0 — CHANGES_REQUESTED** [review]
Please add .env to gitignore

**Review by amurph24 — COMMENTED** [review]
Looks good

**Comment by SpeiserK** [comment]
fixed git ignores, will figure out extra /node_modules in backend section as Aidan suggested

**Review by zachpren0 — APPROVED** [review]
Sweet, nice update to gitignore

**Pull request merged**
