### PR TITLE
Dev tools

### LINKED ISSUE #212: Make devtools for easy testing/checking
- links to certain pages
- test order creation (setting local storage variables to random/test values)

### PR DESCRIPTION
**Pull request by amurph24**
close #212  ;
- devTools have not been implemented anywhere yet, but a component has been created, you can put this on a page when you need easy access to certain things

### CODE REVIEW

**Review by SpeiserK — APPROVED** [review]
Will be nice to have quick access to employee pages, nice.

**Comment by camwlsn** [comment]
Good work on this component, this will allow easy access across pages

**Review by zachpren0 — APPROVED** [review]
Looks good!

**Comment by zachpren0** [comment]
. We needed this. Will
Make out development process much quicker

**Pull request merged**
