### PR TITLE
Admin tool styling

### PR DESCRIPTION
**Pull request by camwlsn**
Added css styling to admin page

### CODE REVIEW

**Comment by camwlsn** [comment]
Css styling on admin tools page
close #145

**Review by amurph24 — APPROVED** [review]
Looking good, on our way to the demo!

**Review by zachpren0 — APPROVED** [review]
Well done on styling

**Review by SpeiserK — APPROVED** [review]
Great changes.

**Review by SpeiserK — CHANGES_REQUESTED** [review]
Change package-lock json

**Pull request closed without merging**
